import type { AccountRole } from "@/lib/auth/roles";
import type { InteractiveMessagePayload } from "@/lib/whatsapp/interactive";

export type {
  InteractiveMessagePayload,
  InteractiveButtonsPayload,
  InteractiveListPayload,
  InteractiveButton,
  InteractiveListRow,
  InteractiveListSection,
} from "@/lib/whatsapp/interactive";

export interface Profile {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  avatar_url?: string;
  /**
   * Legacy free-form role column from migration 001. Never read
   * by the app since 017_account_sharing.sql introduced the typed
   * `account_role` enum. Flagged for removal in a later cleanup
   * migration — kept on the type so existing destructures don't
   * break.
   */
  role: string;
  /**
   * Opted-in beta feature keys for this account. The column survives
   * for future beta gates; no current feature reads it (Flows was
   * the last user and went to soft-GA in PR #134). Defaults to `[]`
   * for every profile; toggled per-account via a direct UPDATE on
   * the `profiles` row.
   */
  beta_features?: string[];
  /**
   * Account this profile is a member of. Added by
   * `017_account_sharing.sql`; NOT NULL in the DB post-backfill.
   * Optional on the type only because older serialised payloads
   * (cached client state, test fixtures) may not have it yet.
   */
  account_id?: string;
  /**
   * Caller's role within their account. Source of truth for every
   * role-gated UI / API check — call `hasMinRole` from
   * `@/lib/auth/roles` rather than comparing this string directly.
   */
  account_role?: AccountRole;
  created_at: string;
}

// ============================================================
// Account-sharing entities (017_account_sharing.sql)
// ============================================================

export interface Account {
  id: string;
  name: string;
  /** auth.users.id of the immutable owner. */
  owner_user_id: string;
  /** IANA timezone scheduled appointment times are read against.
   *  NOT NULL DEFAULT 'America/Sao_Paulo' (migration 044). */
  timezone: string;
  created_at: string;
  updated_at: string;
}

/**
 * Hydrated member row for the Settings → Members tab. Combines
 * the profile and its account_role for a single member of the
 * caller's account. Sensitive fields (email) are populated only
 * when the caller has admin+ — agents and viewers see name +
 * avatar + role only.
 */
export interface AccountMember {
  user_id: string;
  full_name: string;
  email: string | null;
  avatar_url: string | null;
  role: AccountRole;
  joined_at: string;
}

/**
 * Outstanding invite link row. `token_hash` is intentionally
 * absent — it lives only in the DB and on the server. The
 * plaintext token is returned once at creation time and surfaced
 * via the invite URL; never re-emitted.
 */
export interface AccountInvitation {
  id: string;
  account_id: string;
  /** Roles offered via invite — owner is never offered. */
  role: Exclude<AccountRole, "owner">;
  created_by_user_id: string | null;
  label: string | null;
  created_at: string;
  expires_at: string;
  accepted_at: string | null;
  accepted_by_user_id: string | null;
}

export interface Contact {
  id: string;
  user_id: string;
  account_id: string;
  phone: string;
  /** Digits-only form of `phone`, generated by the DB (migration 022)
   *  and unique per account. Read-only. */
  phone_normalized?: string;
  /** CTWA click id captured from the ad-referral block on the first
   *  inbound message of an ad-started conversation (migration 048).
   *  Last click wins; null for an organic contact. */
  ctwa_clid?: string | null;
  /** The ad creative id (migration 048). Diagnostics only, never sent
   *  to Meta. */
  ad_source_id?: string | null;
  /** When `ctwa_clid` was captured (migration 048). */
  ctwa_clid_at?: string | null;
  name?: string;
  email?: string;
  company?: string;
  avatar_url?: string;
  created_at: string;
  updated_at: string;
  /** Hydrated by queries that embed `contact_tags(tags(*))` (e.g. the
   *  Inbox conversation list, for tag filtering). Absent otherwise. */
  tags?: Tag[];
  /** Derived by `normalizeConversation` from an embedded `deals(...)` set:
   *  the contact's most recently created open deal, for the inbox row's
   *  inline stage control. Absent otherwise; null when the contact has no
   *  open deal. */
  primaryDeal?: Deal | null;
}

export interface Tag {
  id: string;
  user_id: string;
  name: string;
  color: string;
  created_at: string;
}

export interface ContactTag {
  id: string;
  contact_id: string;
  tag_id: string;
}

export interface CustomField {
  id: string;
  user_id: string;
  /** Tenancy key — NOT NULL since migration 017. */
  account_id: string;
  field_name: string;
  field_type: string;
  field_options?: Record<string, unknown>;
  created_at: string;
}

export interface ContactCustomValue {
  id: string;
  contact_id: string;
  custom_field_id: string;
  value?: string;
}

export interface ContactNote {
  id: string;
  contact_id: string;
  user_id: string;
  note_text: string;
  created_at: string;
}

export type ConversationStatus = "open" | "pending" | "closed";

export interface Conversation {
  id: string;
  user_id: string;
  contact_id: string;
  status: ConversationStatus;
  assigned_agent_id?: string;
  last_message_text?: string;
  last_message_at?: string;
  unread_count: number;
  created_at: string;
  updated_at: string;
  contact?: Contact;
  /**
   * AI auto-reply state for this thread (migration 029 + 033):
   *  - `ai_autoreply_disabled` — the bot is paused here (a human took
   *    over, or the model handed off). Sticky until re-enabled.
   *  - `ai_reply_count` — how many times the bot has auto-replied,
   *    checked against the account's per-conversation cap.
   *  - `ai_handoff_summary` — short internal note the bot wrote when it
   *    handed off, shown to whoever takes the thread over.
   */
  ai_autoreply_disabled?: boolean;
  ai_reply_count?: number;
  ai_handoff_summary?: string | null;
}

// ============================================================
// Notifications (migration 027)
// ============================================================

export type NotificationType = "conversation_assigned";

export interface Notification {
  id: string;
  account_id: string;
  /** Recipient — the agent this notification is for. */
  user_id: string;
  type: NotificationType;
  conversation_id?: string;
  contact_id?: string;
  /** Who triggered it. Null when an automation/system assigned it. */
  actor_user_id?: string;
  title: string;
  body?: string;
  read_at?: string;
  created_at: string;
}

export type SenderType = "customer" | "agent" | "bot";
export type ContentType =
  | "text"
  | "image"
  | "document"
  | "audio"
  | "video"
  | "location"
  | "template"
  /** Customer tapped a reply button or list row on a message we sent. */
  | "interactive";
export type MessageStatus =
  "sending" | "sent" | "delivered" | "read" | "failed";

export interface Message {
  id: string;
  conversation_id: string;
  sender_type: SenderType;
  sender_id?: string;
  content_type: ContentType;
  content_text?: string;
  media_url?: string;
  /**
   * MIME type of `media_url`'s content, as Meta reported it. Inbound
   * media only — outbound URLs already carry a filename and extension.
   * Null on every row written before migration 039.
   */
  media_type?: string | null;
  template_name?: string;
  message_id?: string;
  status: MessageStatus;
  created_at: string;
  reply_to_message_id?: string;
  /**
   * Only set when `content_type === 'interactive'` — the stable id of
   * the button or list row the customer tapped. The Flows engine uses
   * this to route the next node; the inbox bubble uses it as a styling
   * cue (renders with a "↩ button reply" affordance).
   */
  interactive_reply_id?: string;
  /**
   * Structured payload of an OUTBOUND interactive message (reply
   * buttons or list) we sent. Lets the thread re-render the buttons /
   * rows, not just the body text. Only set when `content_type ===
   * 'interactive'` and `sender_type` is agent/bot. Migration 035.
   */
  interactive_payload?: InteractiveMessagePayload;
  /**
   * True when the AI auto-reply bot generated + sent this message (as
   * opposed to a human agent or a deterministic Flow/automation send,
   * which all share `sender_type='bot'`/`'agent'`). Drives the "AI"
   * badge in the inbox. Migration 033.
   */
  ai_generated?: boolean;
}

export type ReactionActor = "customer" | "agent";

export interface MessageReaction {
  id: string;
  message_id: string;
  conversation_id: string;
  actor_type: ReactionActor;
  actor_id?: string;
  emoji: string;
  created_at: string;
}

/** Mirrors `whatsapp_config.connection_state` (migration 040). */
export type WhatsAppConnectionState =
  "disconnected" | "connecting" | "connected" | "hibernated";

export interface WhatsAppConfig {
  id: string;
  user_id: string;
  /** UAZAPI gateway instance id, set once provisioned. */
  instance_id?: string;
  /**
   * AES-256-GCM-encrypted UAZAPI instance token. Never sent to the
   * client — see whatsapp-connection spec, "Credential protection at
   * rest".
   */
  instance_token?: string;
  /** AES-256-GCM-encrypted per-account webhook callback secret. */
  webhook_secret?: string;
  /** SHA-256 hex digest of webhook_secret — the callback lookup key. */
  webhook_secret_hash?: string;
  connection_state: WhatsAppConnectionState;
  /** E.164 WhatsApp number paired to the instance, once connected. */
  paired_phone?: string;
  paired_at?: string;
  /**
   * When true (the default), the inbound webhook copies received media
   * into the `chat-media` bucket so attachments outlive the gateway's
   * ~7-day retention. Turning it off keeps storage flat and accepts
   * that inbound attachments expire. Migration 039.
   */
  mirror_inbound_media?: boolean;
  /**
   * Opt-in. When both this and `inbound_default_stage_id` are set, the
   * inbound webhook creates one open deal on this pipeline for every
   * contact it newly creates while ingesting a message. Null (the
   * default, and after the pipeline/stage is deleted) disables it.
   * Migration 041.
   */
  inbound_default_pipeline_id?: string | null;
  /** Landing stage for `inbound_default_pipeline_id`. Migration 041. */
  inbound_default_stage_id?: string | null;
}

export interface Pipeline {
  id: string;
  user_id: string;
  name: string;
  created_at: string;
}

export interface PipelineStage {
  id: string;
  pipeline_id: string;
  name: string;
  position: number;
  color: string;
  /**
   * A system stage can't be renamed, deleted, or moved out of
   * position 0 — enforced by DB triggers (migration 046), the UI only
   * hides the controls. At most one per pipeline. Migration 046.
   */
  is_system: boolean;
  created_at: string;
}

export type DealStatus = "open" | "qualified" | "lost";

/** Type of a deal custom field definition (migration 042). */
export type DealFieldType = "text" | "number" | "date" | "select" | "checkbox";

/** Priority band on a deal (migration 042). */
export type DealPriority = "low" | "medium" | "high";

/**
 * Account-wide typed custom field definition for deals (migration 042).
 * Separate catalogue from {@link CustomField}, which is contacts-only —
 * a definition here never appears on a contact and vice versa.
 */
export interface DealCustomField {
  id: string;
  /** Tenancy key. */
  account_id: string;
  /** Author / audit only. */
  user_id: string;
  field_name: string;
  field_type: DealFieldType;
  /**
   * Type-specific config. For `select` this is `{ options: string[] }`
   * with at least one entry (DB CHECK `deal_custom_fields_select_has_options`).
   * Null for every other type.
   */
  field_options?: { options?: string[] } | null;
  /** Display order within the account's catalogue. */
  position: number;
  created_at: string;
  updated_at: string;
}

/**
 * One deal's value for one {@link DealCustomField} (migration 042).
 * `value` is TEXT and interpreted by the definition's `field_type`
 * (see `@/lib/deals/custom-fields`). At most one row per (deal, field).
 */
export interface DealCustomValue {
  id: string;
  deal_id: string;
  field_id: string;
  value?: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * Appendable, attributed deal note (migration 042). Replaces the
 * single overwritable `Deal.notes` field. `user_id` is nullable —
 * removing a teammate orphans the attribution rather than deleting
 * what they wrote.
 */
export interface DealNote {
  id: string;
  deal_id: string;
  user_id: string | null;
  note_text: string;
  created_at: string;
  /** Hydrated when the query embeds `author:profiles(...)`. */
  author?: Pick<
    Profile,
    "id" | "user_id" | "full_name" | "email" | "avatar_url"
  > | null;
}

export interface Deal {
  id: string;
  user_id: string;
  pipeline_id: string;
  stage_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved.
   */
  contact_id: string | null;
  conversation_id?: string;
  assigned_to?: string;
  title: string;
  value: number;
  currency?: string;
  /**
   * DORMANT since migration 042 — deal notes moved to the `deal_notes`
   * table ({@link DealNote}). Retained so the migration is rollback-safe
   * and existing API/webhook consumers keep reading; the editor no
   * longer writes it.
   */
  notes?: string;
  /** UTC ISO instant the lead is booked for; nullable in the DB and
   *  cleared to `null` by the board card's inline scheduling edit.
   *  Read/written against the account's timezone (migration 044). */
  scheduled_at?: string | null;
  /** When the lead confirmed the booking (migration 044). Column
   *  only — no UI in this change reads or writes it. */
  appointment_confirmed_at?: string | null;
  status?: DealStatus;
  /** Win likelihood 0–100 (migration 042). Undefined = not estimated, distinct from 0. */
  probability?: number | null;
  /** Priority band (migration 042). Undefined = unset. */
  priority?: DealPriority | null;
  /** Free-text lead source (migration 042). */
  source?: string | null;
  /** Free-text long description (migration 042). */
  description?: string | null;
  /**
   * Free text captured when the deal is marked lost (migration 042).
   * Deliberately NOT cleared on reopen, so the history survives.
   */
  lost_reason?: string | null;
  /**
   * When the deal was archived (migration 043). `null` / undefined =
   * active. Independent of `status` — a won or lost deal can be
   * archived and keeps its status. Archive is a pipeline-board-view
   * concern only: the board load filters on this, other `deals` reads
   * do not.
   */
  archived_at?: string | null;
  created_at: string;
  updated_at?: string;
  contact?: Contact;
  stage?: PipelineStage;
  pipeline?: Pipeline;
  assignee?: Profile;
}

export type BroadcastStatus =
  "draft" | "scheduled" | "sending" | "sent" | "failed";
export type RecipientStatus =
  "pending" | "sent" | "delivered" | "read" | "replied" | "failed";
export type BroadcastMediaKind = "image" | "video" | "document" | "audio";

export interface Broadcast {
  id: string;
  user_id: string;
  name: string;
  /**
   * Free-form body, optionally containing `{{field}}` placeholders
   * resolved per recipient. Doubles as the caption on a media
   * broadcast. Replaces template_name/template_language (migration
   * 040 — see design.md D5).
   */
  message_body: string;
  /** Optional attachment — a chat-media object URL. */
  media_url?: string | null;
  media_kind?: BroadcastMediaKind | null;
  /** Document-only — shown as the file name in the recipient's chat. */
  media_filename?: string | null;
  /** Per-variable fallback used when a recipient has no value for it. */
  variable_defaults?: Record<string, string> | null;
  audience_filter?: Record<string, unknown>;
  scheduled_at?: string;
  status: BroadcastStatus;
  total_recipients: number;
  sent_count: number;
  delivered_count: number;
  read_count: number;
  replied_count: number;
  failed_count: number;
  /**
   * Set while a server-side delivery pass is fanning out, NULL when
   * idle. Claimed with a conditional UPDATE so two resumes can't both
   * send. Added in migration 038.
   */
  delivery_locked_at?: string | null;
  created_at: string;
}

export interface BroadcastRecipient {
  id: string;
  broadcast_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved; the
   * UI renders "Unknown" for orphaned rows.
   */
  contact_id: string | null;
  status: RecipientStatus;
  sent_at?: string;
  delivered_at?: string;
  read_at?: string;
  replied_at?: string;
  error_message?: string;
  /**
   * The gateway's message id, persisted when the broadcast send
   * succeeds so the webhook can mirror status updates back onto the
   * recipient row. Added in migration 003.
   */
  whatsapp_message_id?: string;
  /**
   * This recipient's resolved `{{field}}` → value map, frozen when the
   * broadcast was planned so a server-side resume reproduces the
   * original pass exactly rather than re-resolving against contact
   * data that may have changed since. Added in migration 038 (as a
   * positional array under Meta templates; repurposed to a named map
   * by migration 040 — see design.md D5).
   */
  template_params?: Record<string, string> | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Automations (migration 006)
// ============================================================

export type AutomationTriggerType =
  | "new_message_received"
  | "first_inbound_message"
  | "keyword_match"
  | "new_contact_created"
  | "conversation_assigned"
  | "tag_added"
  | "time_based"
  /** Customer tapped a reply button / list row whose id matches; lets
   *  multi-step menus be chained across automations. */
  | "interactive_reply";

export type AutomationStepType =
  | "send_message"
  | "send_buttons"
  | "send_list"
  | "add_tag"
  | "remove_tag"
  | "assign_conversation"
  | "update_contact_field"
  | "create_deal"
  | "wait"
  | "condition"
  | "send_webhook"
  | "close_conversation";

export type AutomationLogStatus = "success" | "partial" | "failed";

export interface KeywordMatchTriggerConfig {
  keywords: string[];
  /**
   * `contains` (the default) is a raw substring test, so a short keyword
   * matches inside longer words — "k" fires on "thanks". `word` is the
   * boundary-aware alternative added for issue #409; see
   * `matchesWholeWord` in `@/lib/automations/engine` for its exact
   * semantics. Flows carry their own keyword config and stay
   * substring-only (`@/lib/flows/types`).
   */
  match_type: "exact" | "contains" | "word";
  case_sensitive?: boolean;
}

export interface TagTriggerConfig {
  tag_id: string;
}

export interface TimeBasedTriggerConfig {
  /** Cron expression or simple HH:mm string; engine can accept either. */
  schedule: string;
  timezone?: string;
}

export interface InteractiveReplyTriggerConfig {
  /** Button / list-row ids to match, exact. Any one matching fires. */
  reply_ids: string[];
}

export type AutomationTriggerConfig =
  | Record<string, never>
  | KeywordMatchTriggerConfig
  | TagTriggerConfig
  | TimeBasedTriggerConfig
  | InteractiveReplyTriggerConfig
  | Record<string, unknown>;

export interface SendMessageStepConfig {
  text: string;
}

/**
 * `send_buttons` / `send_list` step configs carry the full interactive
 * payload (same shape stored on messages + quick replies). `kind` is
 * implied by the step_type but kept on the payload for a uniform shape.
 */
export type SendButtonsStepConfig = InteractiveMessagePayload;
export type SendListStepConfig = InteractiveMessagePayload;

export interface TagStepConfig {
  tag_id: string;
}

export interface AssignConversationStepConfig {
  mode: "specific" | "round_robin";
  agent_id?: string;
}

export interface UpdateContactFieldStepConfig {
  /**
   * Either a built-in contact column (`name` | `email` | `company`) or a
   * custom field encoded as `custom:<custom_field_id>`. The `custom:` prefix
   * is how the engine distinguishes a `contact_custom_values` write from a
   * direct `contacts` column update. Older configs store the bare column name,
   * so this stays backward compatible.
   */
  field: string;
  /** Supports `{{ vars.* }}` / `{{ message.text }}` interpolation at runtime. */
  value: string;
}

export interface CreateDealStepConfig {
  pipeline_id: string;
  stage_id: string;
  title: string;
  value?: number;
}

export interface WaitStepConfig {
  amount: number;
  unit: "minutes" | "hours" | "days";
}

export type ConditionSubject =
  "contact_field" | "tag_presence" | "message_content" | "time_of_day";

export interface ConditionStepConfig {
  subject: ConditionSubject;
  /** e.g. field name, tag id, substring, or "HH:mm-HH:mm" depending on subject */
  operand?: string;
  /** For contact_field equals / message_content contains — comparison value */
  value?: string;
}

export interface SendWebhookStepConfig {
  url: string;
  headers?: Record<string, string>;
  body_template?: string;
}

export type AutomationStepConfig =
  | SendMessageStepConfig
  | SendButtonsStepConfig
  | SendListStepConfig
  | TagStepConfig
  | AssignConversationStepConfig
  | UpdateContactFieldStepConfig
  | CreateDealStepConfig
  | WaitStepConfig
  | ConditionStepConfig
  | SendWebhookStepConfig
  | Record<string, never>
  | Record<string, unknown>;

export interface Automation {
  id: string;
  /** Account tenancy key — every automation belongs to one account
   *  (migration 017 made the column NOT NULL). The engine looks up
   *  active automations by this field on inbound webhook events. */
  account_id: string;
  /** Original author. Used for log audit + outbound message
   *  sender-of-record, never for tenancy isolation. */
  user_id: string;
  name: string;
  description?: string;
  trigger_type: AutomationTriggerType;
  trigger_config: AutomationTriggerConfig;
  is_active: boolean;
  execution_count: number;
  last_executed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface AutomationStep {
  id: string;
  automation_id: string;
  parent_step_id?: string | null;
  branch?: "yes" | "no" | null;
  step_type: AutomationStepType;
  step_config: AutomationStepConfig;
  position: number;
  created_at: string;
}

export interface AutomationLogStepResult {
  step_id: string;
  step_type: AutomationStepType;
  status: "success" | "skipped" | "failed";
  detail?: string;
}

export interface AutomationLog {
  id: string;
  automation_id: string;
  user_id: string;
  contact_id: string | null;
  trigger_event: string;
  steps_executed: AutomationLogStepResult[];
  status: AutomationLogStatus;
  error_message?: string | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Quick replies — reusable snippets (migration 035)
// ============================================================

export type QuickReplyKind = "text" | "interactive";

export interface QuickReply {
  id: string;
  /** Account tenancy key — shared across all members of the account. */
  account_id: string;
  /** Author / audit only. */
  user_id: string;
  title: string;
  kind: QuickReplyKind;
  /** Set when `kind === 'text'`. */
  content_text?: string | null;
  /** Set when `kind === 'interactive'`. */
  interactive_payload?: InteractiveMessagePayload | null;
  created_at: string;
  updated_at: string;
}
